import turtle
from turtle import *
import time
import random
turtle.bgcolor("seashell")
pen = turtle.Turtle()
screen = turtle.Screen()
#定义点触发函数：点击打印坐标
def get_pos(x,y) :
    print(f"点击位置坐标：x={x};y={y}")
#-----绑定鼠标点击事件----------------
screen.onclick(get_pos)
#-----------------love------------changeing----------
turtle.bgcolor("pink")
turtle.hideturtle()
penup()
turtle.goto(-22,76)
pendown()
turtle.left(135)
turtle.speed(0)
pendown()
pencolor("red")
fillcolor("red")
begin_fill()
circle(50,180)
forward(100)
turtle.left(90)
forward(100)
circle(50,180)
end_fill()         #------------one love ----------------
turtle.bgcolor("purple")
penup()
turtle.goto(185,224)
turtle.left(270)
fillcolor("red")
begin_fill()
circle(50,180)
forward(100)
turtle.left(90)
forward(100)
circle(50,180)
end_fill()         #------------one love ----------------
turtle.bgcolor("lightblue")
penup()
turtle.goto(-233,222)
fillcolor("red")
turtle.left(270)
begin_fill()
circle(50,180)
forward(100)
turtle.left(90)
forward(100)
circle(50,180)
end_fill()         #------------one love ----------------
turtle.bgcolor("yellow")
penup()
turtle.goto(-245,-122)
fillcolor("red")
turtle.left(270)
begin_fill()
circle(50,180)
forward(100)
turtle.left(90)
forward(100)
circle(50,180)
end_fill()         #------------one love ----------------
turtle.bgcolor("orange")
penup()
turtle.goto(217,-139)
fillcolor("red")
turtle.right(90)
begin_fill()
circle(50,180)
forward(100)
turtle.left(90)
forward(100)
circle(50,180)
end_fill()         #------------one love ----------------
turtle.bgcolor("cyan")
time.sleep(0.1)
turtle.reset()
turtle.hideturtle()
turtle.speed(0)
penup()
turtle.goto(-22,76)
turtle.left(135)
pendown()
pencolor("pink")
fillcolor("pink")
begin_fill()
circle(70,180)
forward(130)
turtle.left(90)
forward(130)
circle(70,180)
end_fill()     #--------------two love---------------------
turtle.bgcolor("magenta")
penup()
turtle.goto(-12,104)
pendown()
turtle.left(275)
turtle.speed(0)
pendown()
pencolor("yellow")
fillcolor("yellow")
begin_fill()
circle(90,180)
forward(165)
turtle.left(85)
forward(165)
circle(90,180)
end_fill() # ---------- three love -------------------
turtle.bgcolor("seashell")
time.sleep(1)
turtle.reset()
turtle.hideturtle()
turtle.speed(10)
screen.onclick(get_pos)
penup()
pencolor("gold")
turtle.write("Happy Mid-Autumn Festival!!!🥰✨✨", align = "center",font = ("Arial",30,"bold"))
#---------------文字祝福开头------------------
wenziyuancolor = ['pink','purple','magenta','cyan','brown','pink']
yuanweizhi = [(-319,75),(-188,-48),(-16,93),(131,-51),(267,85),(306,-32)]
yuansize = [20,30,20,20,30,20]
for wen,weizhi,yuanzizes in zip(wenziyuancolor,yuanweizhi,yuansize) :
    penup()
    turtle.speed(0)
    turtle.goto(weizhi[0],weizhi[1] - yuanzizes)
    pencolor(wen)
    fillcolor(wen)
    begin_fill()
    circle(yuanzizes)
    end_fill()
time.sleep(2)
turtle.reset()
turtle.hideturtle()
turtle.speed(10)
#-------画烟花哈哈-------------------------加文字----
yanhuacolor = ['pink','purple','magenta','cyan','brown','pink','gold','tomato','violet',
               'pink','purple','magenta','cyan','brown','pink','gold','tomato','violet']
angle_1 = [  n * 20 for n in range(18)]
huachima = [20,30,20,40,30,40,50,30,20,50,40,40,30,50,20,40,30,40]
huacenter = [(-319,75),(212,176),(66,-149)]
for center1,center2 in huacenter :
    for yanhua,Angle_1,yanhuachima in zip(yanhuacolor,angle_1,huachima) :
        penup()
        pensize(5)
        pencolor(yanhua)
        turtle.goto(center1,center2)
        turtle.setheading(Angle_1)
        pendown()
        turtle.forward(yanhuachima*3)
#-------------祝福--弹窗嘿嘿(●ˇ∀ˇ●)-----------------
zhufu = [('🥰中秋快乐！❤️阖家团圆✨',--135,131) ,('💛但愿人长久，千里共婵娟🎇🎈',-118,54),
          ('月亮🌙圆圆人团圆💕',-301,-76),('一口月饼一口甜🥮，中秋快乐乐无边',89,-45),
          ('月亮圆圆，💖快乐满满',-208,258)]
for inner,zhufu1,zhufu2 in zhufu :
    penup()
    turtle.goto(zhufu1,zhufu2)
    pencolor('pink')
    turtle.write(inner,align = "center",font = ("幼圆",15,"bold")) 
time.sleep(2)
turtle.reset()
turtle.hideturtle()
turtle.speed(0)
penup()
forward(10)
pensize(5)
pencolor("pink")
fillcolor("pink")
begin_fill()
turtle.left(90)
pendown()
circle(100,180)
turtle.right(60)
circle(40,180)
turtle.right(30)
forward(115)
turtle.right(35)
circle(40,180)
end_fill()
pencolor("white")
fillcolor("white")
begin_fill()
turtle.left(30)
penup()
forward(140)
turtle.right(90)
pendown()
circle(20)
end_fill()
fillcolor("black")
begin_fill()
circle(16)
end_fill()
turtle.right(95)
penup()
forward(90)
pendown()
fillcolor("white")
begin_fill()
circle(20)
end_fill()
fillcolor("black")
begin_fill()
circle(16)
end_fill()
turtle.left(180)
penup()
pencolor("black")
fillcolor("black")
forward(48)
begin_fill()
circle(9)
end_fill()
penup()
turtle.goto(-126,94)
pendown()
pencolor("pink")
fillcolor("pink")
begin_fill()
turtle.right(60)
circle(100,50)
turtle.left(100)
circle(100,50)
end_fill()
turtle.goto(-136,91)
pencolor("white")
fillcolor("white")
begin_fill()
turtle.left(159)
circle(60,50)
turtle.left(100)
circle(60,50)
end_fill()
penup()
turtle.goto(-18,71)
pencolor("pink")
fillcolor("pink")
begin_fill()
turtle.left(100)
circle(100,50)
turtle.left(100)
circle(100,50)
end_fill()
turtle.goto(-26,78)
pencolor('white')
fillcolor('white')
begin_fill()
turtle.left(160)
circle(60,50)
turtle.left(100)
circle(60,50)
end_fill()
penup()
turtle.goto(-89,-14)
pendown()
pencolor('black')
circle(20,180)
penup()
turtle.goto(-89,-14)
pendown()
turtle.left(35)
circle(20,-180)
penup()
turtle.goto(-186,-112)
pencolor("gold")
turtle.write("中秋节快乐呀！", align = "left", font =("幼园",25,"normal"))
colors = ['orange','yellow','yellow','orange','orange','yellow',
          'blue','blue','blue','blue','blue','blue']
positions = [(-235,88),(23,96),(-295,-54),(132,40),(-361,44),(54,-71),
             (-302,111),(-257,10),(-362,-59),(74,-4),(157,-70),(142,116)]
bigsmall = [20,30,30,27,30,25,10,10,10,10,10,10]
for yuancolor,position,size in zip(colors,positions,bigsmall) :
    penup()
    turtle.goto(position[0],position[1] - size)
    pendown()
    pencolor(yuancolor)
    fillcolor(yuancolor)
    begin_fill()
    circle(size)
    end_fill()
time.sleep(2)
turtle.reset()
turtle.hideturtle()
pencolor("gold")
penup()
turtle.goto(-267,130)
turtle.write("花好月圆中秋夜，举杯共饮团圆酒,",align="left",font=("楷体",20))
penup()
turtle.goto(-267,100)
turtle.write("愿你生活如圆月般圆满，心情如月光般明朗，",align="left",font=("楷体",20))
penup()
turtle.goto(-267,70)
turtle.write("日子如月饼般甜蜜", align="left",font=("楷体",20))
penup()
turtle.goto(-267,40)
turtle.write("中秋佳节，祝你和家人幸福安康，万事如意！",  align="left",font=("楷体",20))
turtle.speed(0)
#-----------最后的装饰——-------------------
lication = [(-307,191),(-129,262),(53,196),(245,248),(-300,-20),(-130,-93),(-26,-20),(156,-123),(261,-13)]
colorr = ['pink','purple','magenta','yellow','blue','yellow','pink','purple','blue']
zzz = [20,30,20,30,20,30,30,40,20]
for lic,co,zz in zip(lication,colorr,zzz) :
    penup()
    turtle.speed(0)
    turtle.goto(lic)
    pencolor(co)
    fillcolor(co)
    begin_fill()
    pendown()
    circle(zz)
    end_fill()
time.sleep(2)
backgrand =  ['pink','purple','magenta','yellow','blue','yellow','pink','purple','blue','cyan','seashell']
for grand in backgrand :
    time.sleep(0.1)
    turtle.bgcolor(grand)
turtle.done()